# Generated by Django 3.2.8 on 2021-11-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
