# Generated by Django 3.2.9 on 2021-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211103_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
