# Generated by Django 3.2.9 on 2021-11-19 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_profile_is_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-time_added',)},
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
