# Generated by Django 3.2.9 on 2021-11-22 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20211119_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customers',
            field=models.ManyToManyField(related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
