# Generated by Django 3.2.8 on 2021-11-05 15:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_store_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
