# Generated by Django 3.2.9 on 2021-11-19 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20211119_1509'),
        ('api', '0013_auto_20211109_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='vendororder',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='vendororder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='payee_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
