# Generated by Django 3.2.9 on 2021-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_store_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.Product'),
        ),
        migrations.AddField(
            model_name='store',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='api.Service'),
        ),
    ]
