# Generated by Django 3.2.9 on 2021-11-26 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211124_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
