# Generated by Django 3.2.8 on 2021-11-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='vendor'),
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=20, null=True)),
                ('building', models.CharField(blank=True, max_length=200, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('post', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('isDefault', models.BooleanField(blank=True, default=True)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
