# Generated by Django 3.2.8 on 2021-11-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211102_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
