# Generated by Django 3.2.8 on 2021-10-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211028_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
