# Generated by Django 3.2.8 on 2021-11-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='post',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
