# Generated by Django 3.2.8 on 2021-10-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20211028_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('sdg_goals', models.CharField(choices=[('SDG_Two', 'SDG_Two'), ('SDG_One', 'SDG_One'), ('SDG_Three', 'SDG_Three')], default='SDG_One', max_length=35)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('tags', models.CharField(choices=[('tag2', 'tag2'), ('tag1', 'tag1'), ('tag3', 'tag3')], default='tag1', max_length=35)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_stocked', models.BooleanField(default=False)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
