# Generated by Django 3.2.8 on 2021-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_stocked',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
