# Generated by Django 3.2.8 on 2021-11-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211103_1438'),
        ('api', '0005_alter_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_logo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('tags', models.CharField(blank=True, choices=[('tag2', 'tag2'), ('tag1', 'tag1'), ('tag3', 'tag3')], default='tag1', max_length=35, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(blank=True, default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
