# Generated by Django 3.2.9 on 2021-11-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_store_sdg_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_option', models.CharField(blank=True, max_length=255, null=True)),
                ('payee_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_purchase_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
