# Generated by Django 3.2.9 on 2021-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_storeorder_vendororder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororder',
            name='purchase_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
